version: '2.9'
services:
  postgresdb:
    container_name: postgresdb
    hostname: postgresdb
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    build:
        context: ./code/jvm/
        dockerfile: ./src/main/resources/Dockerfile-db
    ports:
      - 5432:5432
    networks:
      - back-network

  battleship-service-1:
    container_name: battleship-service-1
    hostname: battleship-service-1
    build:
      context: ./code/jvm/
      dockerfile: ./Dockerfile
    environment:
      JDBC_DATABASE_URL: "jdbc:postgresql://postgresdb:5432/postgres?user=postgres&password=postgres"
      PORT: 8081
    ports:
      - 8081:8081
    networks:
      - back-network
    depends_on:
      - postgresdb

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 8080:8080
    volumes:
      - ./code/jvm/:/etc/nginx
    networks:
      - back-network
      - front-network
    depends_on:
      - battleship-service-1

  web_app:
    container_name: web_app
    build:
      context: ./code/js
      dockerfile: ./Dockerfile
    environment:
      - WEB_PORT=3000
      - API_URL=http://localhost:8080
    ports:
      - 3000:3000
    networks:
      - front-network
      - back-network
    depends_on:
      - nginx    
  
networks:
  front-network:
    driver: bridge
  back-network:
    driver: bridge
  
