version: '0.1'
services:
  postgresdb:
    container_name: postgresdb
    hostname: postgresdb
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    build:
        context: .
        dockerfile: ./src/main/resources/Dockerfile-db
    ports:
      - 5432:5432

  battleship-service-1:
    container_name: battleship-service-1
    hostname: battleship-service-1
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      JDBC_DATABASE_URL: "jdbc:postgresql://postgresdb:5432/postgres?user=postgres&password=postgres"
      PORT: 8081
    ports:
      - 8081:8081

  battleship-service-2:
    container_name: battleship-service-2
    hostname: battleship-service-2
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      PORT: 8082
      JDBC_DATABASE_URL: "jdbc:postgresql://postgresdb:5432/postgres?user=postgres&password=postgres"
    ports:
      - 8082:8082

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 8080:8080
    volumes:
      - ./:/etc/nginx
    depends_on:
      - battleship-service-1
      - battleship-service-2